# Generated by Django 2.0 on 2017-12-31 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, default=0, verbose_name='user id')),
                ('openid', models.CharField(db_index=True, max_length=300, verbose_name='微信openid')),
                ('phone', models.CharField(db_index=True, max_length=16, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('pos_id', models.IntegerField(default=None, null=True, verbose_name='位置记录id')),
                ('small_head_img', models.CharField(default='', max_length=500, verbose_name='头像小图')),
                ('big_head_img', models.CharField(default='', max_length=500, verbose_name='头像大图')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.IntegerField(default=None, null=True, verbose_name='经度')),
                ('latitude', models.IntegerField(default=None, null=True, verbose_name='维度')),
                ('zoom', models.IntegerField(default=1, verbose_name='经纬度缩放')),
                ('nation', models.CharField(default=None, max_length=31, null=True, verbose_name='国家')),
                ('province', models.CharField(max_length=100, verbose_name='省/州/自治区')),
                ('city', models.CharField(max_length=100, verbose_name='市')),
                ('region', models.CharField(max_length=100, verbose_name='区/县')),
                ('street', models.CharField(max_length=200, verbose_name='街道')),
                ('detail', models.CharField(max_length=300, verbose_name='详细')),
            ],
            options={
                'db_table': 'position',
            },
        ),
    ]
