# Generated by Django 2.0 on 2017-12-31 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=16, verbose_name='手机号')),
                ('code', models.IntegerField(verbose_name='验证码')),
                ('expiration', models.DateTimeField(verbose_name='过期时间')),
                ('sendtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已用')),
            ],
            options={
                'db_table': 'validate_codes',
            },
        ),
        migrations.AlterIndexTogether(
            name='validatecodes',
            index_together={('phone', 'code')},
        ),
    ]
